BEGIN;

TRUNCATE "User" RESTART IDENTITY CASCADE;
TRUNCATE "RoomType" RESTART IDENTITY CASCADE;
TRUNCATE "Amenity" RESTART IDENTITY CASCADE;
TRUNCATE "Guest" RESTART IDENTITY CASCADE;
TRUNCATE "Reservation" RESTART IDENTITY CASCADE;
TRUNCATE "Consultation" RESTART IDENTITY CASCADE;

-- También truncamos la tabla "pivot" de la relación M2M
TRUNCATE "_GuestToReservation" RESTART IDENTITY CASCADE;

COMMIT;